bnb: 
    id:  'binancecoin'
    concentration:  0.307
okb:  
    id:  'okb'
    concentration:  0.0961
cro:
    id:  'crypto-com-chain'
    concentration:  0.0952
cel:  
    id:  'celsius-degree-token'
    concentration:  0.0928
ftt:  
    id:  'ftx-token'
    concentration:  0.0898
ht:
    id: 'huobi-token'
    concentration:  0.0846
leo: 
    id:  'leo-token'
    concentration:  0.0796
nexo:
    id: 'nexo'
    concentration:  0.0780
kcs:
    id: 'kucoin-shares'
    concentration:  0.0769

